# Generated by Django 5.2 on 2025-04-17 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='client',
        ),
        migrations.AddField(
            model_name='appointment',
            name='car_license',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='car_license',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
