# Generated by Django 5.2 on 2025-04-17 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_app', '0002_remove_appointment_client_appointment_car_license_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='email',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
